### ISSUE TITLE
Not working on .css files, but working perfectly on scss files

### ISSUE THREAD

**Issue by jeevancandy** [spatie/laravel-mix-purgecss#67]
`mix.sass("resources/assets/sass/test_raw.scss", "public/css/test_raw.css")
		.version()
		.purgeCss();`

Which is perfectly working fine. But for the following case(mentioned below) it is not working

`mix.css("resources/assets/css/test.css", "public/css/test.css")
		.version()
		.purgeCss();`

I have 2 questions, 
1. Will it work on mix.css() as my whole project was build with .css but not .scss files(If yes please mention the process)
2. In purgecss documentation I seen that we cannot send an array of files to mix.scss(), they suggested to import all other files to one single scss file, when I am trying that it is converting to "url" and not able to compress those css which I imported, what is the fix for this?

**Comment by sebastiandedeyne** [comment]
What exactly does `mix.css()` do? I don't see it documented anywhere. Assuming `mix.css()` just copies fiels without sending them through webpack, it makes sense that they don't get purged.

I'd suggest you try `mix.postCss("resources/assets/css/test.css", "public/css/test.css")`, that would do the same as `mix.css()`, since you'll just send it through postcss without any plugins, and the css file would be forced through webpack.

> In purgecss documentation I seen that we cannot send an array of files to mix.scss()

Are you confusing the mix documentation with the purgecss documentation? Where is this mentioned? I'm not sure this repo is the correct place for that question.
